### ISSUE TITLE
No such file or directory: '/data/model/0f_1sclean_noise.npz'

### ISSUE THREAD

**Issue by JackNhat** [meokz/looking-to-listen#1]
Thanks for sharing repository,
I tried following the `Quick Start Demonstration` guideline. 
When I ran the command: `docker-compose run network python3 quick_start_audio_only.py /data/model/0f_1sclean_noise.npz /data/noise -ideep` and got the error message `FileNotFoundError: [Errno 2] No such file or directory: '/data/model/0f_1sclean_noise.npz'`.
Where can I download the file `0f_1sclean_noise.npz`?
Thanks for the reply

**Comment by meokz** [comment]
wops,
i forgot to include model file.

please wait for additional commit

**Comment by meokz** [comment]
@JackNhat 
I missed including a pre-training model in the repository.
Now, pre-training model was added.

Please try it
