### ISSUE TITLE
Build failing: unable to build wheel for llvmlite

### ISSUE THREAD

**Issue by th3geek** [meokz/looking-to-listen#11]
Hi,

I've just spent the last 4 hours trying to troubleshoot this error with no luck. It was originally reported in issue #7 by 3 separate users and closed with no reply. I'm running up-to-date Ubuntu 20.04LTS, Docker version 19.03.13, build 4484c46d9d & docker-compose 1.25.0. The other users reporting this error were using Windows and MacOS, so it doesn't seem to be an OS specific problem. Any hints or suggestions would be welcome. Hell, I'll even send you $50 in Bitcoin for your time, just provide your receive address. I really look forward to using it. If you *are* able to get it to build, kindly provide what OS and version of docker & docker-compose you are using.

Thank you.

error below:

  Stored in directory: /root/.cache/pip/wheels/5c/93/0e/45057f13b26ba880ba315b4b580d52ca76151fa88aa5db6db8
  Building wheel for llvmlite (setup.py): started
  Building wheel for llvmlite (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uhcar22w/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uhcar22w/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-um7lksu2
       cwd: /tmp/pip-install-uhcar22w/llvmlite/
  Complete output (26 lines):
  running bdist_wheel
  /usr/bin/python3 /tmp/pip-install-uhcar22w/llvmlite/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/tmp/pip-install-uhcar22w/llvmlite/ffi/build.py", line 106, in main_posix
      out = subprocess.check_output([llvm_config, '--version'])
    File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
      **kwargs).stdout
    File "/usr/lib/python3.5/subprocess.py", line 693, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
      restore_signals, start_new_session)
    File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
      raise child_exception_type(errno_num, err_msg)
  FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/pip-install-uhcar22w/llvmlite/ffi/build.py", line 192, in <module>
      main()
    File "/tmp/pip-install-uhcar22w/llvmlite/ffi/build.py", line 182, in main
      main_posix('linux', '.so')
    File "/tmp/pip-install-uhcar22w/llvmlite/ffi/build.py", line 109, in main_posix
      "to the path for llvm-config" % (llvm_config,))
  RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
  error: command '/usr/bin/python3' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Successfully built librosa termcolor face-recognition-models audioread resampy html5lib
Failed to build llvmlite
Installing collected packages: termcolor, astor, numpy, zipp, importlib-metadata, markdown, html5lib, werkzeug, protobuf, bleach, tensorboard, absl-py, grpcio, gast, tensorflow-gpu, Pillow, face-recognition-models, Click, face-recognition, scipy, opencv-python, kiwisolver, cycler, python-dateutil, matplotlib, audioread, joblib, scikit-learn, decorator, llvmlite, numba, resampy, librosa, certifi, urllib3, chardet, idna, requests
    Running setup.py install for llvmlite: started
    Running setup.py install for llvmlite: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uhcar22w/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uhcar22w/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-l9vbe1m5/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.5/llvmlite
         cwd: /tmp/pip-install-uhcar22w/llvmlite/
    Complete output (29 lines):
    running install
    running build
    got version from file /tmp/pip-install-uhcar22w/llvmlite/llvmlite/_version.py {'version': '0.32.1', 'full': 'aa11b129c0b55973067422397821ae6d44fa5e70'}
    running build_ext
    /usr/bin/python3 /tmp/pip-install-uhcar22w/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-install-uhcar22w/llvmlite/ffi/build.py", line 106, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.5/subprocess.py", line 693, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-uhcar22w/llvmlite/ffi/build.py", line 192, in <module>
        main()
      File "/tmp/pip-install-uhcar22w/llvmlite/ffi/build.py", line 182, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-uhcar22w/llvmlite/ffi/build.py", line 109, in main_posix
        "to the path for llvm-config" % (llvm_config,))
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/usr/bin/python3' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uhcar22w/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uhcar22w/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-l9vbe1m5/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.5/llvmlite Check the logs for full command output.
ERROR: Service 'preprocess' failed to build: The command '/bin/sh -c pip3 install -r /tmp-pip/requirements.txt     && rm -rf /tmp-pip' returned a non-zero code: 1

**Comment by th3geek** [comment]
OK, so the problem is: librosa doesn't support python3.5 at all. I'm trying to figure out how to install python3.4 but not having any luck and python3.6 isn't support by xenial so I'm kinda stuck i guess... I tried to compile python3.4 from source, but I'm getting errors.Would love a hint if anyone sees this.

**Comment by th3geek** [comment]
OK, I've installed python3.4 using the deadsnake ppa, but python3.5 is *still* being installed by other packages and simply trying to remove 3.5 with apt doesn't work. I'm now looking into pyenv to specify python3.4 as the default python3

**Comment by xlabd** [comment]
@th3geek check out my PR #12. Do the appropriate changes to the files. When you execute `docker-compose build`, you won't get any errors.

**Comment by th3geek** [comment]
Thank you very much!

**Comment by meokz** [comment]
@xlabd 
Thank you for your contributions!
