### ISSUE TITLE
librosa 0.8 does not support output function so need to switch to soundfile package for writing audio file

### ISSUE THREAD

**Issue by saumyaborwankar** [meokz/looking-to-listen#15]
File "/home/saumya/looking-to-listen/network/src/common/util.py", line 81, in istft_and_save
    librosa.output.write_wav(path=filepath, y=signal, sr=settings.SR, norm=True)
AttributeError: module 'librosa' has no attribute 'output'

**Comment by saumyaborwankar** [comment]
File "/home/saumya/noise_reduce/looking-to-listen/network/src/common/util.py", line 81, in istft_and_save
    librosa.output.write_wav(path=filepath, y=signal, sr=settings.SR, norm=True)
AttributeError: module 'librosa' has no attribute 'output'

**Comment by saumyaborwankar** [comment]
I have written the code to remove this error but im not sure how to make a pull request. Im quite new to github
Maybe you can include it in the source code so the package will be compatible with librosa 0.8

**Comment by meokz** [comment]
We fixed the version of librosa at 0.6.3
You can see requirements.txt in https://github.com/meokz/looking-to-listen/blob/master/preprocess/requirements.txt.

Versions different from requirements.txt are not guaranteed.
