### ISSUE TITLE
I can't install "llvmlite"

### ISSUE THREAD

**Issue by muchojp** [meokz/looking-to-listen#7]
When I entered this command 'docker-compose build', the WARNING raised 

ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0xgjyd6t/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0xgjyd6t/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-s12tyn7m
       cwd: /tmp/pip-install-0xgjyd6t/llvmlite/
  Complete output (26 lines):
  running bdist_wheel
  /usr/bin/python3 /tmp/pip-install-0xgjyd6t/llvmlite/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/tmp/pip-install-0xgjyd6t/llvmlite/ffi/build.py", line 106, in main_posix
      out = subprocess.check_output([llvm_config, '--version'])
    File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
      **kwargs).stdout
    File "/usr/lib/python3.5/subprocess.py", line 693, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
      restore_signals, start_new_session)
    File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
      raise child_exception_type(errno_num, err_msg)
  FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/tmp/pip-install-0xgjyd6t/llvmlite/ffi/build.py", line 192, in <module>
      main()
    File "/tmp/pip-install-0xgjyd6t/llvmlite/ffi/build.py", line 182, in main
      main_posix('linux', '.so')
    File "/tmp/pip-install-0xgjyd6t/llvmlite/ffi/build.py", line 109, in main_posix
      "to the path for llvm-config" % (llvm_config,))
  RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
  error: command '/usr/bin/python3' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite

Is this meant I can't install llvmlite because I am WINDOWS user? However, I am using docker, something strange. If someone know how to solve this problem, please tell me.

**Comment by ilawson1997** [comment]
I am having the exact same issue on macOS, were you able to solve this?

**Comment by xlabd** [comment]
I have the same error. Did you find a solution @ilawson1997, @muchojp?
